import Navbar from '@/components/Navbar';
import './globals.css'

export const metadata = {
  title: 'Projeto API TMDB',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className='bg-zinc-800 text-white'>
        <Navbar />
        {children}
      </body>
    </html>
  )
};